import Foundation

enum AppData {
    static let startingBalance = 10_000
    static let sports = [
        "Football", "Basketball", "Tennis", "American Football", "Baseball",
        "Ice Hockey", "Cricket", "Boxing", "MMA / UFC", "Esports", "Rugby",
        "Golf", "Formula 1", "Handball", "Volleyball"
    ]

    static let tips: [BettingTip] = [
        .init(id: 1, category: .strategy, title: "Bankroll Management is Fundamental", detail: "Never risk more than 1-3% of your total bankroll on a single bet.", content: "Proper bankroll management is the cornerstone of successful betting. By limiting your stake to 1-3% of your total bankroll per bet, you protect yourself from devastating losing streaks and ensure you can continue betting even during rough patches. This conservative approach allows for long-term sustainability and prevents emotional decision-making.", keyTakeaway: "Discipline in stake sizing is more important than picking winners.", relatedTipIDs: [2,5]),
        .init(id: 2, category: .mathematics, title: "Understanding Expected Value (EV)", detail: "EV = (Probability of Winning × Amount Won) - (Probability of Losing × Amount Lost)", content: "Expected Value is the cornerstone of profitable betting. It represents the average amount you can expect to win or lose per bet over the long run. A positive EV bet (+EV) means you have an edge, while negative EV (-EV) means the bookmaker has the advantage. Always seek +EV opportunities by comparing your probability assessments with the odds offered.", keyTakeaway: "Focus on finding +EV bets, not just picking winners.", relatedTipIDs: [4,7]),
        .init(id: 3, category: .psychology, title: "Avoid the Gambler's Fallacy", detail: "Each bet is independent - past results don't affect future outcomes.", content: "The gambler's fallacy is the mistaken belief that past events influence future independent events. Just because a team has lost five games in a row doesn't mean they're 'due' for a win. Each game is an independent event with its own probabilities. Make decisions based on current form, statistics, and analysis, not on perceived patterns.", keyTakeaway: "", relatedTipIDs: [8,12]),
        .init(id: 4, category: .mathematics, title: "The Kelly Criterion for Optimal Sizing", detail: "Kelly % = (bp - q) / b, where b is odds, p is win probability, q is loss probability.", content: "The Kelly Criterion is a mathematical formula used to determine the optimal bet size to maximize long-term growth. While full Kelly can be aggressive and lead to high variance, many professional bettors use fractional Kelly (1/4 or 1/2 Kelly) for more conservative growth. This method ensures you're betting more on high-confidence, +EV opportunities and less on marginal edges.", keyTakeaway: "Use fractional Kelly for sustainable bankroll growth with reduced volatility.", relatedTipIDs: [1,2]),
        .init(id: 5, category: .strategy, title: "Line Shopping Increases Profit", detail: "Always compare odds across multiple bookmakers before placing a bet.", content: "Line shopping means comparing odds across different sportsbooks to find the best price for your bet. Even small differences in odds compound significantly over time. For example, consistently getting odds of 2.10 instead of 2.00 can be the difference between profit and loss over hundreds of bets. Maintain accounts with multiple reputable bookmakers and always check for the best available line.", keyTakeaway: "A 5% improvement in odds can turn a losing strategy into a winning one.", relatedTipIDs: [2,11]),
        .init(id: 6, category: .psychology, title: "Embrace Variance and Losing Streaks", detail: "Even the best strategies will experience losing streaks - it's mathematics, not failure.", content: "Variance is an unavoidable part of betting. Even with a 60% win rate, you can easily experience streaks of 5-10 consecutive losses due to random variance. Understanding and accepting this is crucial for long-term success. Don't abandon a profitable strategy after a losing streak, and don't chase losses by increasing bet sizes. Trust your process, maintain discipline, and let the mathematics work over large sample sizes.", keyTakeaway: "Losing streaks are normal - focus on process, not short-term results.", relatedTipIDs: [1,3]),
        .init(id: 7, category: .analysis, title: "Context Matters More Than Statistics", detail: "Raw statistics without context can be misleading.", content: "While statistics are important, they must be interpreted with context. A team's goal-scoring average might look impressive, but if most goals came against weak opponents, this inflates their true ability. Consider factors like strength of schedule, home/away performance, recent form, injuries, motivation, and weather conditions. Advanced metrics like xG (expected goals) can provide deeper insights than raw statistics.", keyTakeaway: "Always ask 'why' behind the numbers - context creates edges.", relatedTipIDs: [10,15]),
        .init(id: 8, category: .psychology, title: "Avoid Betting on Your Favorite Team", detail: "Emotional attachment clouds judgment and leads to biased analysis.", content: "One of the most common mistakes is betting on teams you emotionally support. Bias causes you to overestimate your team's chances, ignore warning signs, and make irrational decisions. If you must bet on your favorite team, apply extra scrutiny to your analysis and consider whether you'd make the same bet if it were any other team in the same situation. Often, the best decision is to simply avoid betting on games involving your team.", keyTakeaway: "Emotional attachment is the enemy of profitable betting.", relatedTipIDs: [3,6]),
        .init(id: 9, category: .strategy, title: "Specialize in Specific Markets", detail: "Deep knowledge in one area beats surface knowledge in many.", content: "Rather than spreading yourself thin across multiple sports and markets, develop deep expertise in a specific niche. Whether it's NBA totals, European football corners, or tennis first-set betting, specialized knowledge gives you an edge over bookmakers and casual bettors. Follow specific leagues closely, understand the nuances, and become an expert rather than a generalist.", keyTakeaway: "Specialization creates information advantages and sustainable edges.", relatedTipIDs: [7,11]),
        .init(id: 10, category: .analysis, title: "Reverse Line Movement (RLM) Signals Sharp Action", detail: "When odds move against public betting percentages, sharp money is usually involved.", content: "Reverse Line Movement occurs when betting odds move in the opposite direction of public betting percentages. For example, if 70% of bets are on Team A, but the odds move to make Team B more attractive, this suggests that sharp bettors (professionals) are heavily backing Team B with larger stakes. RLM can be a valuable indicator of where smart money is positioned, though it should be one factor among many in your analysis.", keyTakeaway: "Follow the money, not the crowd - sharp action moves lines.", relatedTipIDs: [5,13]),
        .init(id: 11, category: .strategy, title: "Keep Detailed Records", detail: "Track every bet to identify strengths, weaknesses, and profitability patterns.", content: "Maintaining a comprehensive betting journal is essential for long-term success. Record every bet with details: date, sport, market, stake, odds, result, and reasoning. Regularly analyze your records to identify which sports, bet types, or situations are most profitable. This data-driven approach helps you double down on what works and eliminate losing strategies. Without records, you're betting blind.", keyTakeaway: "If you're not tracking, you're not learning - data reveals truth.", relatedTipIDs: [9,16]),
        .init(id: 12, category: .psychology, title: "Never Chase Losses", detail: "Increasing stakes after losses to 'win back' money is a path to ruin.", content: "Chasing losses is one of the fastest ways to destroy your bankroll. After a losing streak, the temptation to increase bet sizes to quickly recover losses is strong, but this emotional response violates disciplined bankroll management. Losses are part of the game. Stick to your predetermined staking plan regardless of recent results. Remember: one big loss can wipe out weeks of careful profit.", keyTakeaway: "Discipline during losses separates successful bettors from failures.", relatedTipIDs: [1,6]),
        .init(id: 13, category: .analysis, title: "Closing Line Value (CLV) Measures Skill", detail: "Consistently beating the closing line is the hallmark of sharp betting.", content: "Closing Line Value measures whether you got better odds than what was available just before game time. The closing line is generally the most efficient (accurate) line because it incorporates all available information and sharp betting action. If you consistently beat the closing line, you're demonstrating market-beating skill. Track your CLV over time as a key performance indicator beyond simple win-loss records.", keyTakeaway: "Beating the closing line consistently = long-term profitability.", relatedTipIDs: [10,14]),
        .init(id: 14, category: .mathematics, title: "Implied Probability vs True Probability", detail: "Convert odds to implied probability and compare it to your assessment.", content: "Every odds format can be converted to implied probability. For decimal odds, the formula is: Implied Probability = 1 / Decimal Odds. For example, odds of 2.00 represent 50% implied probability. However, this includes the bookmaker's margin (vig). To find value, calculate your own true probability estimate and compare it to the implied probability. If your true probability is higher than the implied probability, you've found a +EV bet.", keyTakeaway: "Value exists where your probability assessment exceeds market expectations.", relatedTipIDs: [2,4]),
        .init(id: 15, category: .analysis, title: "Home Field Advantage Varies by Sport", detail: "Quantify home advantage for each sport and league you bet on.", content: "Home field advantage is real but varies significantly by sport. NBA home teams win approximately 60% of games, while MLB home teams win around 54%. Even within sports, certain venues or teams have stronger home advantages. Research and quantify home advantage for your specific markets, but also recognize when it's overpriced. Just because a team is home doesn't automatically make them a good bet if the odds already overcompensate for this edge.", keyTakeaway: "Know the typical home advantage, then find games where it's mispriced.", relatedTipIDs: [7,9]),
        .init(id: 16, category: .strategy, title: "Value Betting Over Outcome Prediction", detail: "Profitability comes from finding mispriced odds, not predicting outcomes.", content: "Many beginners focus solely on predicting winners, but profitable betting is about finding value - situations where odds are mispriced relative to true probability. You can lose a value bet and still have made a good decision. Conversely, winning a -EV bet was still a bad decision. Over thousands of bets, consistent value betting produces profit regardless of short-term outcomes. Shift your mindset from 'who will win?' to 'where is the value?'", keyTakeaway: "Good bets can lose, bad bets can win - focus on value, not outcomes.", relatedTipIDs: [2,14]),
        .init(id: 17, category: .strategy, title: "Understand Bookmaker Margins", detail: "The 'vig' or 'juice' is the bookmaker's built-in profit margin.", content: "Bookmakers build a margin into their odds to ensure profitability regardless of outcome. For example, a fair coin flip should have odds of 2.00 on both sides (50% implied probability each = 100% total). But bookmakers might offer 1.91 on both sides (52.4% implied probability each = 104.8% total). That 4.8% overround is their margin. Understanding this margin helps you calculate true probabilities and identify which bookmakers offer the most competitive pricing.", keyTakeaway: "Lower margins = better value for bettors - shop for the best pricing.", relatedTipIDs: [5,14]),
        .init(id: 18, category: .psychology, title: "Set Win and Loss Limits", detail: "Predetermined stop points prevent emotional decision-making.", content: "Before each betting session, set both win and loss limits. If you reach either limit, stop betting for that session. This prevents the euphoria of winning from causing overconfidence and bigger risks, and it prevents the desperation of losing from causing chase behavior. These limits aren't about the amounts themselves, but about maintaining emotional control and discipline in your decision-making process.", keyTakeaway: "Limits protect you from your emotions during both wins and losses.", relatedTipIDs: [6,12]),
        .init(id: 19, category: .analysis, title: "Late Injury News Creates Opportunities", detail: "React quickly to breaking news before bookmakers adjust lines.", content: "Late-breaking news like surprise injuries or lineup changes can create brief windows of opportunity before bookmakers adjust their odds. However, this requires fast action, reliable information sources, and pre-established accounts with funded balances. Be cautious: ensure the news is from legitimate sources before acting, as false rumors are common. Also recognize that by the time news is widely known, the edge has usually disappeared.", keyTakeaway: "Speed and reliable information sources create short-term value opportunities.", relatedTipIDs: [10,13]),
        .init(id: 20, category: .strategy, title: "Long-Term Thinking Wins", detail: "Success in betting is measured over thousands of bets, not individual days.", content: "The single most important mindset for betting success is long-term thinking. Don't judge your strategy by daily or weekly results. Focus on making +EV decisions consistently and let the mathematics work over large sample sizes (thousands of bets). Keep emotions in check, maintain discipline, continuously learn and adapt, and remember that sustainable profit is a marathon, not a sprint. The bettors who survive and thrive are those who think in years, not days.", keyTakeaway: "Daily results are noise - long-term process is the only signal that matters.", relatedTipIDs: [6,11])
    ]

    static let quizQuestions: [QuizQuestion] = [
        question(1, "What does ROI mean in sports betting?", ["Stake size", "Return on Investment", "A betting market", "Tax on winnings"], 1, "ROI measures profit or loss relative to the amount staked."),
        question(2, "What does a -1.5 handicap mean in football?", ["The team may lose by one", "The team must win by two or more", "Exactly two goals", "The match must be drawn"], 1, "A -1.5 handicap requires a margin of at least two goals."),
        question(3, "Which strategy doubles the stake after a loss?", ["Flat staking", "D'Alembert", "Martingale", "Arbitrage"], 2, "Martingale increases the next stake after a loss and carries substantial risk."),
        question(4, "What is a bookmaker margin?", ["Profit built into the odds", "A player bonus", "An analyst error", "A refunded stake"], 0, "The margin is the bookmaker's mathematical advantage across a market."),
        question(5, "What combines several selections that all must win?", ["Single", "Accumulator", "Total", "Handicap"], 1, "An accumulator requires every included selection to win."),
        question(6, "In which sport is a slam dunk common?", ["Ice hockey", "Basketball", "Tennis", "Volleyball"], 1, "A slam dunk is a basketball scoring move."),
        question(7, "What does over 2.5 goals mean?", ["At least three goals", "Exactly two goals", "A three-goal winning margin", "A red card"], 0, "The total number of goals must be three or more."),
        question(8, "Which surface is used at Wimbledon?", ["Hard", "Clay", "Grass", "Carpet"], 2, "Wimbledon is played on grass courts."),
        question(9, "What is a value bet?", ["A bet on the favorite", "Your probability exceeds the odds-implied probability", "A free bet", "An exact-score bet"], 1, "Value exists when your estimated chance is better than the market price suggests."),
        question(10, "How many regulation periods are in ice hockey?", ["2", "3", "4", "Unlimited"], 1, "A regulation ice hockey game has three periods."),
        question(11, "What does both teams to score — yes require?", ["Either team to win", "Both teams to score at least once", "An own goal", "No goals"], 1, "Each team must score one or more goals."),
        question(12, "Which country is considered the birthplace of the Olympic Games?", ["Italy", "England", "Greece", "France"], 2, "The ancient Olympic Games originated in Greece."),
        question(13, "What is cash out?", ["A bookmaker bankruptcy", "Early settlement before an event ends", "A bank withdrawal", "A loan"], 1, "Cash out settles a bet before the underlying event is complete."),
        question(14, "How long is a standard professional boxing round?", ["2 minutes", "3 minutes", "5 minutes", "10 minutes"], 1, "Standard professional rounds are three minutes."),
        question(15, "How many players does one football team field?", ["10", "11", "12", "9"], 1, "A football team normally has eleven players on the field."),
        question(16, "What does double chance 1X mean?", ["Home win or draw", "Exact score 1–0", "Home handicap", "Canceled match"], 0, "1X covers a home win and a draw."),
        question(17, "Which sport is not in a classic triathlon?", ["Swimming", "Cycling", "Running", "Tennis"], 3, "A classic triathlon combines swimming, cycling, and running."),
        question(18, "What is a sharp drop in odds after heavy betting commonly called?", ["Line movement", "Arbitrage", "Cash out", "Flat staking"], 0, "Concentrated action or new information can move a betting line."),
        question(19, "Which competition awards the European Champion Clubs' Cup?", ["Europa League", "UEFA Champions League", "Copa Libertadores", "FIFA World Cup"], 1, "The trophy is awarded to the UEFA Champions League winner."),
        question(20, "What is flat staking?", ["Doubling after a loss", "Backing an underdog", "Using a fixed stake or percentage", "Buying predictions"], 2, "Flat staking keeps the amount or bankroll percentage consistent.")
    ]

    private static func question(
        _ id: Int,
        _ prompt: String,
        _ answers: [String],
        _ correctIndex: Int,
        _ explanation: String
    ) -> QuizQuestion {
        QuizQuestion(id: id, prompt: prompt, answers: answers, correctIndex: correctIndex, explanation: explanation)
    }
}
